# Generated by Django 4.2 on 2023-05-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userprofile_profile_pic_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
    ]
