# A key value store of all countries with their country codes.
# The countries are sorted alphabetically
# Updated as of September 2021
CHOICES = [
	("AF", "Afghanistan"),
	("AL", "Albania"),
	("DZ", "Algeria"),
	("AD", "Andorra"),
	("AO", "Angola"),
	("AG", "Antigua and Barbuda"),
	("AR", "Argentina"),
	("AM", "Armenia"),
	("AU", "Australia"),
	("AT", "Austria"),
	("AZ", "Azerbaijan"),
	("BS", "Bahamas"),
	("BH", "Bahrain"),
	("BD", "Bangladesh"),
	("BB", "Barbados"),
	("BY", "Belarus"),
	("BE", "Belgium"),
	("BZ", "Belize"),
	("BJ", "Benin"),
	("BT", "Bhutan"),
	("BO", "Bolivia"),
	("BA", "Bosnia and Herzegovina"),
	("BW", "Botswana"),
	("BR", "Brazil"),
	("BN", "Brunei Darussalam"),
	("BG", "Bulgaria"),
	("BF", "Burkina Faso"),
	("BI", "Burundi"),
	("CV", "Cabo Verde"),
	("KH", "Cambodia"),
	("CM", "Cameroon"),
	("CA", "Canada"),
	("CF", "Central African Republic"),
	("TD", "Chad"),
	("CL", "Chile"),
	("CN", "China"),
	("CO", "Colombia"),
	("KM", "Comoros"),
	("CG", "Congo"),
	("CR", "Costa Rica"),
	("CI", "Côte d'Ivoire"),
	("HR", "Croatia"),
	("CU", "Cuba"),
	("CY", "Cyprus"),
	("CZ", "Czech Republic"),
	("KP", "Democratic People's Republic of Korea"),
	("CD", "Democratic Republic of the Congo"),
	("DK", "Denmark"),
	("DJ", "Djibouti"),
	("DM", "Dominica"),
	("DO", "Dominican Republic"),
	("EC", "Ecuador"),
	("EG", "Egypt"),
	("SV", "El Salvador"),
	("GQ", "Equatorial Guinea"),
	("ER", "Eritrea"),
	("EE", "Estonia"),
	("SZ", "Eswatini"),
	("ET", "Ethiopia"),
	("FJ", "Fiji"),
	("FI", "Finland"),
	("FR", "France"),
	("GA", "Gabon"),
	("GM", "Gambia"),
	("GE", "Georgia"),
	("DE", "Germany"),
	("GH", "Ghana"),
	("GR", "Greece"),
	("GD", "Grenada"),
	("GT", "Guatemala"),
	("GN", "Guinea"),
	("GW", "Guinea-Bissau"),
	("GY", "Guyana"),
	("GN", "Guinea"),
	("GW", "Guinea-Bissau"),
	("GY", "Guyana"),
	("HT", "Haiti"),
	("HM", "Heard Island and McDonald Islands"),
	("VA", "Holy See"),
	("HN", "Honduras"),
	("HK", "Hong Kong"),
	("HU", "Hungary"),
	("IS", "Iceland"),
	("IN", "India"),
	("ID", "Indonesia"),
	("IR", "Iran (Islamic Republic of)"),
	("IQ", "Iraq"),
	("IE", "Ireland"),
	("IM", "Isle of Man"),
	("IL", "Israel"),
	("IT", "Italy"),
	("JM", "Jamaica"),
	("JP", "Japan"),
	("JE", "Jersey"),
	("JO", "Jordan"),
	("KZ", "Kazakhstan"),
	("KE", "Kenya"),
	("KI", "Kiribati"),
	("KW", "Kuwait"),
	("KG", "Kyrgyzstan"),
	("LA", "Lao People's Democratic Republic"),
	("LV", "Latvia"),
	("LB", "Lebanon"),
	("LS", "Lesotho"),
	("LR", "Liberia"),
	("LY", "Libya"),
	("LI", "Liechtenstein"),
	("LT", "Lithuania"),
	("LU", "Luxembourg"),
	("MO", "Macao"),
	("MK", "North Macedonia"),
	("MG", "Madagascar"),
	("MW", "Malawi"),
	("MY", "Malaysia"),
	("MV", "Maldives"),
	("ML", "Mali"),
	("MT", "Malta"),
	("MH", "Marshall Islands"),
	("MQ", "Martinique"),
	("MR", "Mauritania"),
	("MU", "Mauritius"),
	("YT", "Mayotte"),
	("MX", "Mexico"),
	("FM", "Micronesia (Federated States of)"),
	("MD", "Moldova (Republic of)"),
	("MC", "Monaco"),
	("MN", "Mongolia"),
	("ME", "Montenegro"),
	("MS", "Montserrat"),
	("MA", "Morocco"),
	("MZ", "Mozambique"),
	("MM", "Myanmar"),
	("NA", "Namibia"),
	("NR", "Nauru"),
	("NP", "Nepal"),
	("NL", "Netherlands"),
	("NC", "New Caledonia"),
	("NZ", "New Zealand"),
	("NI", "Nicaragua"),
	("NE", "Niger"),
	("NG", "Nigeria"),
	("NU", "Niue"),
	("NF", "Norfolk Island"),
	("KP", "Korea (Democratic People's Republic of)"),
	("MP", "Northern Mariana Islands"),
	("NO", "Norway"),
	("OM", "Oman"),
	("PK", "Pakistan"),
	("PW", "Palau"),
	("PS", "Palestine, State of"),
	("PA", "Panama"),
	("PG", "Papua New Guinea"),
	("PY", "Paraguay"),
	("PE", "Peru"),
	("PH", "Philippines"),
	("PN", "Pitcairn"),
	("PL", "Poland"),
	("PT", "Portugal"),
	("QA", "Qatar"),
	("RO", "Romania"),
	("RU", "Russia"),
	("RW", "Rwanda"),
	("KN", "Saint Kitts and Nevis"),
	("LC", "Saint Lucia"),
	("VC", "Saint Vincent and the Grenadines"),
	("WS", "Samoa"),
	("SM", "San Marino"),
	("ST", "Sao Tome and Principe"),
	("SA", "Saudi Arabia"),
	("SN", "Senegal"),
	("RS", "Serbia"),
	("SC", "Seychelles"),
	("SL", "Sierra Leone"),
	("SG", "Singapore"),
	("SK", "Slovakia"),
	("SI", "Slovenia"),
	("SB", "Solomon Islands"),
	("SO", "Somalia"),
	("ZA", "South Africa"),
	("KR", "South Korea"),
	("SS", "South Sudan"),
	("ES", "Spain"),
	("LK", "Sri Lanka"),
	("SD", "Sudan"),
	("SR", "Suriname"),
	("SE", "Sweden"),
	("CH", "Switzerland"),
	("SY", "Syria"),
	("TW", "Taiwan"),
	("TJ", "Tajikistan"),
	("TZ", "Tanzania"),
	("TH", "Thailand"),
	("TL", "Timor-Leste"),
	("TG", "Togo"),
	("TO", "Tonga"),
	("TT", "Trinidad and Tobago"),
	("TN", "Tunisia"),
	("TR", "Turkey"),
	("TM", "Turkmenistan"),
	("TV", "Tuvalu"),
	("UG", "Uganda"),
	("UA", "Ukraine"),
	("AE", "United Arab Emirates"),
	("GB", "United Kingdom"),
	("US", "United States of America"),
	("UY", "Uruguay"),
	("UZ", "Uzbekistan"),
	("VU", "Vanuatu"),
	("VE", "Venezuela"),
	("VN", "Vietnam"),
	("YE", "Yemen"),
	("ZM", "Zambia"),
	("ZW", "Zimbabwe")
]

LIST = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo",
	"Costa Rica",
	"Côte d'Ivoire",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Democratic People's Republic of Korea",
	"Democratic Republic of the Congo",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"North Macedonia",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia (Federated States of)",
	"Moldova (Republic of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Korea (Democratic People's Republic of)",
	"Northern Mariana Islands",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine, State of",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Qatar",
	"Romania",
	"Russia",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Korea",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Zambia",
	"Zimbabwe"
]
